name: Telegram Notification
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    environment:
      name: telegram

    steps:
      - name: send telegram message on push or pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>LMS Backend Event</b>: 
            <i>${{ github.event_name }} by ${{ github.actor }}</i>

            Commit message: 
            <code>${{ github.event.commits[0].message }}</code>

            Repository: ${{ github.repository }}
            <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">See changes</a>
